vim.api.nvim_set_keymap("n", "<leader>h", [[ :lua require("harpoon.ui").toggle_quick_menu()<CR>]], {noremap = true, silent = true})--, expr = false})
vim.api.nvim_set_keymap("n", "<leader>a", [[ :lua require("harpoon.mark").add_file()<CR>]],        {noremap = true, silent = true})--, expr = false})
vim.api.nvim_set_keymap("n", "<leader>n", [[ :lua require("harpoon.ui").nav_file(1)<CR>]],         {noremap = true, silent = true})--, expr = false})
vim.api.nvim_set_keymap("n", "<leader>e", [[ :lua require("harpoon.ui").nav_file(2)<CR>]],         {noremap = true, silent = true})--, expr = false})
vim.api.nvim_set_keymap("n", "<leader>i", [[ :lua require("harpoon.ui").nav_file(3)<CR>]],         {noremap = true, silent = true})--, expr = false})
vim.api.nvim_set_keymap("n", "<leader>o", [[ :lua require("harpoon.ui").nav_file(4)<CR>]],         {noremap = true, silent = true})--, expr = false})
